# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      # ------ macOS-specific steps BEGIN ------
      - name: Install gettext (macOS only)
        if: runner.os == 'macOS'
        run: brew install gettext

      - name: Set Makevars for gettext (macOS only)
        if: runner.os == 'macOS'
        run: |
          BREW_PREFIX=$(brew --prefix gettext)
          echo "Homebrew gettext prefix: $BREW_PREFIX"
          echo "Contents of $BREW_PREFIX/include:"
          ls -l "$BREW_PREFIX/include"
          echo "Contents of $BREW_PREFIX/lib:"
          ls -l "$BREW_PREFIX/lib"
          mkdir -p ~/.R
          echo "CPPFLAGS += -I${BREW_PREFIX}/include" >> ~/.R/Makevars
          echo "LDFLAGS += -L${BREW_PREFIX}/lib" >> ~/.R/Makevars
      # ------ macOS-specific steps END ------

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
